### ISSUE TITLE
Feature request: Allow to set license duration

### ISSUE THREAD

**Issue by sammkj** [ymotongpoo/vsc-licenser#27]
Would you be open to adding something like below:

```
/**
 * Copyright (C) 2017-present Kok Sam.
 *
 * ....(truncated).....
 */
```

**Comment by dlech** [comment]
This can be accomplished with #23.

**Comment by ymotongpoo** [comment]
@sammkj yes, thanks to the contribution from @dlech, this functionality works with custom license header feature. But if you just want to change license duration part in existing license, let me know your concrete idea. Since, "present" in the license duration sounds not reasonable to me. "present" is relative word to express the time, whereas I believe the license duration part should be written in absolute time.

**Comment by Swat-SomeBug** [comment]
Hi @ymotongpoo I’m also interested in this feature where I would like to add only a license duration.
My proposal would be to enable the use of an additional configuration variable called `YEAR.START`.
When the variable is set the license, the `<year>` part of the license file and header should be replaced with `YEAR.START-YEAR`.

**Comment by ymotongpoo** [comment]
@Swat-SomeBug thanks for the comment. Again, I repeat that I don't come up with the concrete use cases where this feature should be included for whole licenses, so I don't put priority on this FR.
