### ISSUE TITLE
feature request: provide a option for only create license header in `LICENSE` file.

### ISSUE THREAD

**Issue by Cologler** [ymotongpoo/vsc-licenser#28]
Just make project more clean.

**Comment by ymotongpoo** [comment]
it's not valid use of LICENSE file. Do you find any OSS that allow the projects to use license header as license description? Please reopen the issue and give me some examples if you find any.

**Comment by Cologler** [comment]
Maybe what I describe is not very accurate.

The currently behavior is:

1. create the `LICENSE` file in root folder.
1. create license header in other files, like `README.md`.

expected behavior:

1. create the `LICENSE` file in root folder.
1. **DO NOT** create license header in other files.

**Comment by ymotongpoo** [comment]
Do you come up with names of exceptional filenames, such as `README.md`, `COPYING` and so on? At least, I'll force embedding license headers for source files in this extension, but I agree for those exceptions.

**Comment by Cologler** [comment]
You should not force embedding license headers for source files because some source files do not use `//` as comment, like python.
Also, when the source script run on linux, the first line must be `#!/usr/bin/env *`.

**Comment by ymotongpoo** [comment]
> You should not force embedding license headers for source files because some source files do not use // as comment, like python.

As far as I read your comment, this is not a feature request but a bug, because this extension is changes the comment notation based on the file extension. For instance, `#` should be selected as comment notation for Python source files as written in the [notation.ts](https://github.com/ymotongpoo/vsc-licenser/blob/develop/src/notation.ts#L85)

 > Also, when the source script run on linux, the first line must be #!/usr/bin/env *
This is also a bug if the license header is not skipping first line when there is shebang. (the process for it is done [here](https://github.com/ymotongpoo/vsc-licenser/blob/develop/src/extension.ts#L184))

So can you raise bugs for respective symptoms if you see the unintended behavior with latest version.

**Comment by Cologler** [comment]
Not everyone needs the license headers break destroy their custom headers.

**Comment by ymotongpoo** [comment]
> Not everyone needs the license headers break destroy their custom headers.

Then can you give me examples for the "custom headers"? Otherwise the ideas for the options to exclude files where the auto insertion of the default license header should be avoided? Current behavior is usual on IDEs or many other plugins for other editors.

Though you mention "everyone", I just got the comments only from "you" and I'd love to accept constructive opinions to improve this extensions rather than complains. Otherwise you can send me a patch for your expected behavior. This is personal OSS project and I'm building this as my hobby.

**Comment by Cologler** [comment]
like this:

![picpick-20170525-195105-001](https://cloud.githubusercontent.com/assets/10906962/26449191/75a6fe46-4183-11e7-97ac-4999f70d3de8.png)

**Comment by ymotongpoo** [comment]
So, are the first 4 lines inserted from this extension? Then can you raise a bug for it with detailed reproduce procedure? I'm not a magician and I don't want to take a time to find out the repro environment. Thanks.

**Comment by Cologler** [comment]
Even if the first 4 lines is not a not bug, that does not mean I need them.

**Comment by ymotongpoo** [comment]
Freeze this thread since I can't get constructive opinions.
