### ISSUE TITLE
Wrong multi-line comment tag for bash

### ISSUE THREAD

**Issue by maximeB** [ymotongpoo/vsc-licenser#85]
## Runtime environment
* OS (version): windows10
* VS Code version: 1.48.2
* VS Code build number (if possible):
* other extensions installed: many, but it's not relevant here

### Expected behavior

On bash script regardless of setting "licenser.useSingleLineStyle" license header shall always fallback to single line comment using #

### Actual behavior
It uses multi-line comment with "<<LICENSE", ">>" as begin/end tag which is not valid (there is no multi-line comment in bash)

## Steps to reproduce the issue
1. set "licenser.useSingleLineStyle" to false
2. open a bash script without license header
3. insert license header

## Notes:
src/notation.ts defines multi-line comments' begin/end tag for shellscript

**Comment by tevosouza** [comment]
Hello @maximeB,
By default, shell script doesn't support multi-line comments but exists one way to do it using HereDoc.
Take a look [here](https://linuxize.com/post/bash-comments/#multiline-comments-in-bash)

I made a PR (#95) fixing this problem because I understand if the shell doesn't support it as a native feature I see no sense to create an optional dependency that breaks the extension feature.

Do you have any thoughts about it @ymotongpoo?
